### ISSUE TITLE
Errors while initiating AwsRingHttpSigner

### ISSUE THREAD

**Issue by mosheka** [Ekman/aws-ring-http-signer#4]
Hi Team! 
Amazing job forking this project and creating something better and new!

We tried to implement query to Elasticsearch by trying to use part of the tests:

```
$credentials = new Credentials(getenv('AWS_ACCESS_KEY_ID'), getenv('AWS_SECRET_ACCESS_KEY'));
            $credentialsProvider = CredentialProvider::fromCredentials($credentials);
            $signature = new SignatureV4("es", getenv('AWS_REGION'));
            $handler = new AwsRingHttpSigner($signature, $credentialsProvider);

            $this->client = ClientBuilder::create()
                    ->setHandler($handler)
                    ->setHosts([getenv('ES_ENDPOINT')])
                    ->build();
```

However, when we run the code, we get the following error, that claims reg. error in the signature structure

```
Fatal error: Uncaught TypeError: Argument 1 passed to Nekman\AwsRingHttpSigne\AwsRingHttpSigner::__invoke() must be callable, array given, called in /code/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 234 and defined in /code/vendor/nekman/aws-ring-http-signer/src/AwsRingHttpSigner.php:50
Stack trace:
#0 /code/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(234): Nekman\AwsRingHttpSigner\AwsRingHttpSigner->__invoke(Array)
#1 /code/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(211): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
```

Any hint you can provide?

**Comment by Ekman** [comment]
Hi,

Glad you like it!

The `AwsRingHttpSigner` is not an actual handler, but rather a middleware that will intercept request and sign them for you. It still needs a handler in order to send the actual request.

You'll need to wrap the middleware like this:

```php
$credentials = new Credentials(getenv('AWS_ACCESS_KEY_ID'), getenv('AWS_SECRET_ACCESS_KEY'));
$credentialsProvider = CredentialProvider::fromCredentials($credentials);
$signature = new SignatureV4("es", getenv('AWS_REGION'));
// This is what you'll need to do
$awsHandler = new AwsRingHttpSigner($signature, $credentialsProvider);
$handler = $awsHandler(\Elasticsearch\ClientBuilder::defaultHandler());

$this->client = ClientBuilder::create()
     ->setHandler($handler)
     ->setHosts([getenv('ES_ENDPOINT')])
     ->build();
```
